
LDDIR 		:= $(COREDIR)/ld
CONFIG_FILE := $(wildcard $(COREDIR)/.config)

ifeq ($(CONFIG_FILE),)
ifeq ($(MAKECMDGOALS),)
$(error STM32 core config is not found. Please make menuconfig first.)
endif
else
include $(COREDIR)/.config
endif

MCU = -mcpu=$(patsubst "%",%,$(CONFIG_CPU_CORE)) -mthumb -mfloat-abi=soft

ifeq ($(CONFIG_MCU_SERIES),"STM32F103xB")
LDSCRIPT := $(LDDIR)/STM32F103C8TX_FLASH.ld
else
ifeq ($(CONFIG_MCU_SERIES), "STM32F429xx")
LDSCRIPT := $(LDDIR)/STM32F429ZITX_RAM.ld
endif
endif

LDFLAGS = $(MCU) \
	$(addprefix -T,$(LDSCRIPT)) \
	-Wl,-Map=$(OUTDIR)/$(PROJECT_NAME).map,--cref \
	-Wl,--gc-section \
	-static \
	-specs=nano.specs \
	-Wl,--start-group -lc -lm -Wl,--end-group
export CFLAGS LDFLAGS

