
LDDIR 		:= ld
CONFIG_FILE := $(wildcard $(COREDIR)/.config)

ifeq ($(CONFIG_FILE),)
ifeq ($(MAKECMDGOALS),)
$(error STM32 core config is not found. Please make menuconfig first.)
endif
else
include $(COREDIR)/.config
endif

ifeq ($(CONFIG_MCU_SERIES),"STM32F103xB")
LDSCRIPT := $(LDDIR)/STM32F103C8TX_FLASH.ld
endif

all:
