-include $(TOPDIR)/.config

obj-$(CONFIG_MCU_FAMILY_F4) += STM32F4xx_HAL_Driver/
obj-$(CONFIG_MCU_FAMILY_F4) += system_stm32f4xx.o
obj-$(CONFIG_MCU_FAMILY_F1) += STM32F1xx_HAL_Driver/
obj-$(CONFIG_MCU_FAMILY_F1) += system_stm32f1xx.o
